export default [
  {
    id: '0841fd90-b372-4421-802d-4de909f8f950',
    content: '/Window[@ClassName=\\"Window\\"][@Name=\\"Some Desktop Application\\"]/Button[@ClassName=\\"Button\\"][@Name=\\"Errors Suck!\\"]',
    hasMissedAlert: true,
    missedAlerts: 21,
    numberOfSubscriptions: 15,
  },
  {
    id: '6dad108e-21e9-4b68-8ba0-0b28ffd299bd',
    content: '/Window[@ClassName=\\"Window\\"][@Name=\\"Some Desktop Application\\"]/Button[@ClassName=\\"Button\\"][@Name=\\"Errors Suck!\\"]',
    hasMissedAlert: true,
    missedAlerts: 3,
    numberOfSubscriptions: 3,
  },
  {
    id: 'a9ff2f3e-11c2-4f3f-9fe9-c12283ad4580',
    content: '/Window[@ClassName=\\"Window\\"][@Name=\\"Some Desktop Application\\"]/Button[@ClassName=\\"Button\\"][@Name=\\"Errors Suck!\\"]',
    hasMissedAlert: true,
    missedAlerts: 1,
    numberOfSubscriptions: 18,
  },
  {
    id: 'd84732fe-0bcc-4340-abc6-5cc726a76c5a',
    content: '/Window[@ClassName=\\"Window\\"][@Name=\\"Some Desktop Application\\"]/Button[@ClassName=\\"Button\\"][@Name=\\"Errors Suck!\\"]',
    hasMissedAlert: false,
    missedAlerts: 0,
    numberOfSubscriptions: 2,
  },
  {
    id: '802c74ee-fde4-4d53-be9c-ff1e9586b141',
    content: '/Window[@ClassName=\\"Window\\"][@Name=\\"Some Desktop Application\\"]/Button[@ClassName=\\"Button\\"][@Name=\\"Errors Suck!\\"]',
    hasMissedAlert: false,
    missedAlerts: 0,
    numberOfSubscriptions: 1,
  },
  {
    id: 'da15ce26-946e-46f1-bd6c-80ea5177a971',
    content: '/Window[@ClassName=\\"Window\\"][@Name=\\"Some Desktop Application\\"]/Button[@ClassName=\\"Button\\"][@Name=\\"Errors Suck!\\"]',
    hasMissedAlert: true,
    missedAlerts: 5,
    numberOfSubscriptions: 6,
  },
  {
    id: '5fbf3d53-b9af-4c66-8e2b-09f8e66899e0',
    content: '/Window[@ClassName=\\"Window\\"][@Name=\\"Some Desktop Application\\"]/Button[@ClassName=\\"Button\\"][@Name=\\"Errors Suck!\\"]',
    hasMissedAlert: false,
    missedAlerts: 0,
    numberOfSubscriptions: 2,
  },
  {
    id: '6e538989-3924-4036-8e9b-ebcb82f98039',
    content: '/Window[@ClassName=\\"Window\\"][@Name=\\"Some Desktop Application\\"]/Button[@ClassName=\\"Button\\"][@Name=\\"Errors Suck!\\"]',
    hasMissedAlert: true,
    missedAlerts: 2,
    numberOfSubscriptions: 8,
  },
  {
    id: '0d3117b0-22c1-411c-8d17-24366ab3a76c',
    content: '/Window[@ClassName=\\"Window\\"][@Name=\\"Some Desktop Application\\"]/Button[@ClassName=\\"Button\\"][@Name=\\"Errors Suck!\\"]',
    hasMissedAlert: true,
    missedAlerts: 2,
    numberOfSubscriptions: 12,
  },
];